spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/users/*/events/*/likes,/users/*/events/*/likes/**

        - id: request-service-user-event
          uri: lb://request-service
          predicates:
            - Path=/users/*/events/*/requests,/users/*/events/*/requests/**

        - id: request-service-user
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests,/users/*/requests/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users,/admin/users/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**,/categories/**,/compilations/**,/admin/events/**,/admin/categories/**,/admin/compilations/**,/users/*/events,/users/*/events/**

        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/**

logging:
  level:
    root: info
    org.springframework.cloud.gateway: DEBUG
