spring:
  sql.init:
    mode: ALWAYS
    schema-locations: classpath:schema-postgres.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6546/ewm-rating
    username: dbuser
    password: 12345
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: true

logging:
  level:
    root: info