CREATE TABLE IF NOT EXISTS public.categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_name ON categories (name);

CREATE TABLE IF NOT EXISTS public.events (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    annotation varchar(2000) NOT NULL,
    created_on timestamp(3) without time zone NOT NULL,
    description varchar(7000) NOT NULL,
    event_date timestamp(3) without time zone NOT NULL,
    location jsonb NOT NULL,
    paid boolean NOT NULL,
    participant_limit integer NOT NULL,
    published_on timestamp(3) without time zone,
    request_moderation boolean NOT NULL,
    state varchar(255) check (state in ('PENDING','PUBLISHED','CANCELED')) NOT NULL,
    title varchar(120) NOT NULL,
    category_id bigint NOT NULL,
    initiator_id bigint NOT NULL,
    rate bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_categories FOREIGN KEY (category_id)
        REFERENCES public.categories (id)
);

CREATE TABLE IF NOT EXISTS public.compilations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pinned boolean NOT NULL,
    title varchar(50) NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.compilation_events (
    compilation_id bigint NOT NULL,
    event_id bigint NOT NULL,
    CONSTRAINT fk_compilation_events_compilations FOREIGN KEY (compilation_id)
        REFERENCES public.compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_events_events FOREIGN KEY (event_id)
        REFERENCES public.events (id) ON DELETE CASCADE
);